# Generated by Django 4.1.4 on 2022-12-08 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appProyectos', '0002_proyecto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usuario',
        ),
    ]
