# Generated by Django 4.1.4 on 2022-12-08 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appProyectos', '0003_delete_usuario'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='proyecto',
            table=None,
        ),
    ]
