# Generated by Django 4.1.4 on 2022-12-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProyectos', '0005_alter_proyecto_options_remove_proyecto_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='foto_img',
            field=models.ImageField(blank=True, null=True, upload_to='proyect_file'),
        ),
    ]
