# Generated by Django 4.1.4 on 2022-12-09 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProyectos', '0006_alter_proyecto_foto_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='foto_img',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='proyect_file'),
        ),
    ]
