# Generated by Django 4.1.4 on 2022-12-08 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0002_alter_profile_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gitPerfil',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedPerfil',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
