# Generated by Django 4.1.4 on 2022-12-08 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0003_profile_gitperfil_profile_linkedperfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='profile',
            name='servicios',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
