# Generated by Django 4.1.4 on 2022-12-08 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0004_alter_profile_about_alter_profile_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'profile', 'verbose_name_plural': 'profiles'},
        ),
    ]
