# Generated by Django 4.1.4 on 2022-12-11 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0006_visitante'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Visitante',
            new_name='VisitanteGeneral',
        ),
    ]
