# Generated by Django 4.1.4 on 2022-12-11 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0008_visitanteportafolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitanteportafolio',
            name='ipVisitante',
            field=models.GenericIPAddressField(unique=True),
        ),
    ]
