# Generated by Django 4.1.4 on 2022-12-11 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0009_alter_visitanteportafolio_ipvisitante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitanteportafolio',
            name='ipVisitante',
            field=models.GenericIPAddressField(),
        ),
    ]
